getwd()
library(wordcloud)
library(RTextTools)
library(tm)
texts<-readLines(file.choose())
docs<-Corpus(VectorSource(texts))
docs<-tm_map(docs,tolower())
docs<-tm_map(docs,removeWords(),stopwords('english'))
docs<-tm_map(docs,removeNumbers())
docs<-tm_map(docs,removePunctuation())
docs<-tm_map(docs,stripWhitespace())
docs<-tm_map(docs,stemDocument())
tdm<-TermDocumentMatrix(docs)
m<-as.matrix(tdm)
s<-sort(rowSums(m),decreasing = FALSE)
d<-data.frame(word=names(s),freq=s)
head(d,10)
wordcloud(d$word,freq = d$freq,max.words = 40,min.freq = 1,random.order = FALSE,random.color = FALSE,rot.per = 0.35)