getwd()
library(igraph)
g<-graph(c(1,2,2,3,4,4,1),n=7,directed = F)
g<-graph(c("A","B","B","C","C","A","D"),directed = F)
plot(g)
g[]
degree(g,mode = "all")
degree(g,mode="in")
degree(g,mode = "out")
closeness(g,mode = "all",weights = NULL)
betweenness(g,directed = F,weights = NULL)
edge.betweenness(g,directed = F,weights = NULL)
cliques(g,min = NULL,max = NULL)
clique.number(g)
clique_num(g)
transitivity(g)
components(g,mode = c("weak","strong"))
plot(g)
neighborhood.size(g)
cohesive.blocks(g)